### ISSUE TITLE
Help please- creating a survival model from an adapative lasso cox approach

### ISSUE THREAD

**Issue by Foinhaven** [ocbe-uio/survomics#8]
Firstly, I wanted to say thank you. This tutorial has been invaluable for me, who is new to this field. 

I was hoping to ask a question with regard to how to progress further my model, if that was okay?

I have been using your tutorial to work through a proteomic dataset of patients with pleural malignancy. I have a dataset of ~1300 proteins and survival data and have used an Adaptive Lasso Cox Model. This has enabled me to identify 18 proteins that are assoc with survival (using the optimal Lambda). 

I have followed your tutorial and have tried to "validate" this in a further cohort. However, I have two questions;

What I am struggling to understand is _what is the _model?__ As in, when I apply this model to a new validation cohort, what am I actually applying? Is it the coefficients of each protein? How can I visualise this, or make it accessible to another person outside of the realms of R?

![image](https://github.com/user-attachments/assets/600b2c41-9c55-4d19-acf0-58b99d0d8074)

**Comment by zhizuio** [comment]
Hello!

If you are following our the code in [Discrimination metrics](https://ocbe-uio.github.io/survomics/survomics.html#discrimination-metrics) or [Overall metrics](https://ocbe-uio.github.io/survomics/survomics.html#overall-metrics), then you are applying your 18 identified proteins and their estimated coefficients for validation. To check the estimated effects of all proteins, you can use the following code (as shown in our [tutorial](https://github.com/ocbe-uio/survomics/blob/8b1669820b86840aff31d34a03df9d7eb9901947/survomics.qmd#L540)) to return their values. Of course, you can filter out zero coefficients in `betas` and only report the coefficients (or exponential of coefficients: hazard ratio (HR)) of the identified 18 proteins.

```r
cvfit <- cv.glmnet(x, y, family = "cox", nfolds = 5, penalty.factor = weights)
mod <- cvfit$glmnet.fit
lambda_optimal <- cvfit$lambda.min # optimal lambda

betas <- as.vector(coef(mod, s = lambda_optimal))
```
